name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        version: ['3.1', '3.2', '3.3']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: benchmark
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - run: bundle exec rake test
